# Generated by Django 5.1.4 on 2024-12-22 18:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_remove_warehouse_store_warehouse_store_city'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdeliverwarehouse',
            name='user',
            field=models.ForeignKey(limit_choices_to={'role': 'buyer'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Покупатель'),
        ),
        migrations.AlterField(
            model_name='customerdeliverwarehouse',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.warehouse', verbose_name='Склад'),
        ),
    ]
