# Generated by Django 5.1.4 on 2024-12-22 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_remove_warehouse_store_warehouse_store_city'),
        ('users', '0002_alter_customerdeliverwarehouse_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='city',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.city', verbose_name='Город'),
        ),
    ]
