# Generated by Django 5.1.4 on 2024-12-22 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('store', '0003_alter_city_name_alter_store_name_city_city_name_idx_and_more'),
        ('users', '0003_customuser_city'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='customerdeliverwarehouse',
            index=models.Index(fields=['user'], name='customer_user_idx'),
        ),
        migrations.AddIndex(
            model_name='customerdeliverwarehouse',
            index=models.Index(fields=['warehouse'], name='customer_warehouse_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['email'], name='customuser_email_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['role'], name='customuser_role_idx'),
        ),
    ]
