# Generated by Django 5.1.4 on 2024-12-22 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_remove_warehouse_store_warehouse_store_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Название города'),
        ),
        migrations.AlterField(
            model_name='store',
            name='name',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Название Магазина'),
        ),
        migrations.AddIndex(
            model_name='city',
            index=models.Index(fields=['name'], name='city_name_idx'),
        ),
        migrations.AddIndex(
            model_name='store',
            index=models.Index(fields=['name'], name='store_name_idx'),
        ),
        migrations.AddIndex(
            model_name='storecity',
            index=models.Index(fields=['store', 'city'], name='store_city_idx'),
        ),
        migrations.AddIndex(
            model_name='warehouse',
            index=models.Index(fields=['store_city'], name='warehouse_store_city_idx'),
        ),
    ]
