# Generated by Django 5.1.4 on 2024-12-22 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productstock',
            options={'verbose_name': 'Остатки Товара', 'verbose_name_plural': 'Остатки Товаров'},
        ),
    ]
