# Generated by Django 5.1.4 on 2024-12-22 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_productstock_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productstock',
            old_name='stock',
            new_name='ware_house',
        ),
    ]
