# Generated by Django 5.1.4 on 2024-12-22 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_rename_stock_productstock_ware_house'),
        ('store', '0002_remove_warehouse_store_warehouse_store_city'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productstock',
            unique_together={('product', 'ware_house')},
        ),
    ]
