# Generated by Django 5.1.4 on 2024-12-22 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_productstock_unique_together'),
        ('store', '0002_remove_warehouse_store_warehouse_store_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='productphoto',
            name='city',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_photo', to='store.city', verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='productphoto',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_photo', to='catalog.product', verbose_name='Товар'),
        ),
    ]
