# Generated by Django 5.1.4 on 2024-12-22 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_productphoto_city_alter_productphoto_product'),
        ('store', '0003_alter_city_name_alter_store_name_city_city_name_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['name'], name='product_name_idx'),
        ),
        migrations.AddIndex(
            model_name='productdescription',
            index=models.Index(fields=['product'], name='productdescription_product_idx'),
        ),
        migrations.AddIndex(
            model_name='productphoto',
            index=models.Index(fields=['product', 'city'], name='productphoto_product_city_idx'),
        ),
        migrations.AddIndex(
            model_name='productstock',
            index=models.Index(fields=['product', 'ware_house'], name='product_stock__idx'),
        ),
    ]
